- name: Expose App with ClusterIP Service
  hosts: localhost
  gather_facts: no
  vars:
    app_name:  my-car-game-app
    container_port: 3000
  tasks:
    - name: Create Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ app_name }}-svc"
            namespace: myapp
          spec:
            selector:
              app: "{{ app_name }}"
            ports:
              - protocol: TCP
                port: 80
                targetPort: "{{ container_port }}"
            type: ClusterIP
