---
- name: Deploy Apache2 web server on EC2
  hosts: web
  become: yes
  gather_facts: yes
  vars_files:
    - var.yaml

  tasks:
    - name: Ping the EC2 instance
      ping:

    - name: Install Apache2 web server
      apt:
        name: apache2
        state: present
        update_cache: yes
      register: apache_result

    - name: Show Apache installation result
      debug:
        var: apache_result

    - name: Start and enable apache2 service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Ensure /var/www/html directory exists
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy custom index.html
      copy:
        src: /workspaces/Ansible/Ansible-lampstack-deployment/index.html
        dest: /var/www/html/index.html

    - name: Verify index.html exists
      stat:
        path: /var/www/html/index.html
      register: webfile

    - name: Show the file creation result
      debug:
        var: webfile.stat
