---
- name: Install NGINX and MySQL on EC2 for CloudWatch Logging
  hosts: web
  gather_facts: yes
  become: yes
  vars_files:
    - var.yaml

  vars:
    mysql_root_user: root
    mysql_root_password: root
    mysql_user: myuser
    mysql_password: mypass
    mysql_database: mydb

  tasks:

    - name: Update the EC2 machine
      apt:
        update_cache: yes
        cache_valid_time: 3000

    - name: Install Python and PyMySQL dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python3-pymysql
        state: present

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Start and enable MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set root password and authentication plugin
      command: >
        mysql -u root -e
        "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
      args:
        creates: /var/lib/mysql/.ansible-password-reset

    - name: Create marker file so password reset is not repeated
      file:
        path: /var/lib/mysql/.ansible-password-reset
        state: touch

    - name: Ensure MySQL database is created
      mysql_db:
        name: "{{ mysql_database }}"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        host: "%"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
