- name: Install Docker and pull image from Docker Hub
  hosts: web
  become: yes
  gather_facts: yes
  vars_files:
    - var.yaml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python 3 and pip on remote
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Log in to Docker Hub
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull
        force_source: true

    - name: Running docker container
      docker_container:
        name: "{{ image_name | regex_replace('/', '_') }}_container"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"
